### ISSUE TITLE
Ruby seems quite slow

### ISSUE THREAD

**Issue by rye** [kotct/language-comparison#1]
I've basically duplicated the source from the C example, but it's like 2x-4x slower when using Ruby. It seems like it's not very optimized. I don't know.

Can I tag people who aren't working on the project? @btgeek? Any ideas?

I'm speaking about `/Primes/Generate N Primes/Ruby/main.rb`, is there something I could do to make it significantly more efficient?

**Comment by rye** [comment]
Looks like I can. That's cool.

**Comment by braddoeswebdev** [comment]
Indeed.  I can't think of anything you could be doing better off the top of my head - but I'm sure I'll think of something sooner or later :wink:

**Comment by rye** [comment]
I mean, to me, the way I did it seems to make sense and be practically a more functional-programming-y version of the same code. So, I'm not sure.

**Comment by cg505** [comment]
It likely is due to the high-levelness of Ruby and stuff like GC. Lisp will probably be the same but I didn't have enough time to run the test.

**Comment by cg505** [comment]
Yeah.. we went past the sqrt.
