### ISSUE TITLE
Language Discussion

### ISSUE THREAD

**Issue by rye** [kotct/language-comparison#2]
From what I've seen, C outperforms everybody in the prime generation algorithm. It has taken Ruby, LISP, and C++ much longer.

I think people can edit comments. At least, I'm pretty sure people can. So I'll start a list and people can add to it.
# C

Time for 10,000 primes: 0.020 s
## Pros:
- _Very_ fast
- Very low-level
- Quite fundamental, easy to think about.
## Cons:
- Hardly functional
- Not object-oriented.
  - Structs could easily be used to imitate classes, with function pointers.
- Requires more effort.
  - We'd have to do a bit of array-y magic and function declarations.
  - Must think significantly about memory.
# C++

Time for 10,000 primes: 0.246 s
## Pros:
- Object-oriented.
- C-like in syntax, with more keywords and storage structures.
  - Slightly more syntactically sane.
## Cons:
- Built-in data structures are slower than C-based equivalents.
- Takes forever to compile.
# LISP

Time for 10,000 primes: 2.284 s (CCL), 4.684 (CLISP), 7.06 (CMUCL)
## Pros:
- Debugging is a million times easier.
- Very small, easy to set up huge operations.
- Memory isn't much of an issue.
  - Maximums for values don't need to be considered.
- Uniform syntax.
- Lots of obscure functions that do crazy high-level stuff.
## Cons (get it? ;]):
- Much different from other languages.
  - Harder for @four04 to understand
- Lots of obscure functions that do crazy high-level stuff.
- Very slow.
# Ruby

Time for 10,000 primes:  0.649 s
## Pros:
- Object-oriented.
- Simple.
- Very human-readable.
- Better debugging that C and C++.
## Cons:
# Issues to Consider
## Debugging

IMO (@cg505) this is the primary concern. When working with complex systems, it is very important to be able to easily and quickly debug because oftentimes there is a small error that only causes problems far down the road. Tracking the issue back to its origin is exponentially harder with the complexity of the system.

Without a doubt, LISP is the clear winner here. The debugging utilities you can get from IDEs like SLIME are incredible and go beyond anything I've found for any other language.

Ruby I would say is the next up, due to the fact that, like LISP, it can run in a REPL. inferior-ruby-mode for emacs feels kind of like slime, but lacking some of the really nice features (namely, stepping through programs, examining variables mid-way through execution, and similar fun things).

C and C++ share a point on this issue because they are essentially equally easy to debug. GDB is _the_ debugging tool here, and it provides those things that Ruby lacks. Unfortunately, it also lacks those things that Ruby has (namely, a REPL and related features). However, the main downside to this pair of languages is that they have little to no error handling. For example, if you go out of bounds on an array, who knows what will happen. If you do that in LISP or Ruby, an error will be thrown.
## Familiarity

This is mainly an issue to those of like @NevetssteveN who are not familiar with any language that does not use curly braces. While we all are able to learn languages without too much difficulty, it is obviously easier to use a language that we know already.

We all know C, and @four04 knows it to a ridiculous degree. This is a clear winner here.

C++ is next, in a similar situation. @four04 probably knows it the best, and we all know a little of it. We are all less familiar with it than C, though.

Ruby is next up, due to the fact that it was used extensively by @samercier, @four04, and @cg505 last year in making [team461WBI/website](https://github.com/team461WBI/website). It's intricacies remain somewhat mystic to us, however.

LISP is last on this one. While @cg505 understands it a very deep level, it's pretty mystic and strange to everyone else. IMO (@cg505) it's not to hard to learn, but it's completely different than pretty much any other language you've used. @samercier has some knowledge via clojure and @four04 some via emacs lisp, but it is my understanding that this is fairly minimal.
## Coding ease

This category can be more specifically defined by answering the following question: Assuming you know each language equally, in which can you write (not debug) code the fastest, with the fewest unexpected bugs? This is very important I would hope for obvious reasons. IMO (@cg505) this is more important than runtime speed (to a degree).

IMO (@cg505) LISP wins this one. An argument could be made for Ruby, but I think due to cool super-high-level functions like some and loop (just to name a few), LISP is faster. Also, GC, lists, and bignums are awesome.

Ruby. The code for ruby in the Generate N Primes code is actually shorter than the lisp code if you take out the newlines and the comments. It also has a lot of the cool things that LISP has like map and anonymous functions, plus object-orientedness. You could definitely make the argument that Ruby beats LISP on this.

C++ is way below the previous two, but beats C. You're getting into some dirty stuff, but you still have some nice things (vectors, object-orientedness(-ish), streams).

If you're using C, ~~you're getting your hands dirty. Memory has to be thought about very carefully, pointers must be checked, and you've got to remember that strcmp returns the opposite of what actually makes sense.~~ you're going to have to spend more time working at a lower level than if you aren't. C requires manual work with the operating system to obtain memory, but at the same time allows you more control over how you do said manual work with any storage structures. The common C programmer would argue that you have no need for special object-oriented stuff or advanced built-in storage structures because they allow you less freedom in terms of speed, they slow things down, and they're a sign that you're lazy.
## Speed

Not as big of an issue, but it's a nice plus. I doubt that anything we write will end up being too processor-intensive, but being able to do stuff fast looks good to non-programmers.

C is like lightning. Holy ****. It is ridiculous. There must be a bug in that primes code it runs so fast.

C++ is an order of magnitude slower than C.

Ruby is slower than C++, but still on the same order of magnitude.

LISP. Really, really slow. Like, over 100x slower than C. Wow.

**Comment by cg505** [comment]
Please add in the times for 2,000,000 gen'd primes to get a sense of speed diffs.

**Comment by cg505** [comment]
Added 10,000

**Comment by rye** [comment]
I'll write a script to automate that soon.

**Comment by rye** [comment]
Okay, let me add some stuff.

Firstly, I very-much-so enjoy C. It's not hard to deal with, and you can build very advanced systems (cite Linux, etc.) with a relatively simple amount of code. The code is more low-level, therefore, you can put it on pretty-much any system; the only issues are how you deal with the system you're running on, and that's where stuff breaks. The language itself works everywhere. _That's not new, however, this is:_

When writing C code, you can very easily write debugging code. It certainly cannot be natively as simple as LISP's debugging is without doing a lot of hacky tree-y crap (the way I see being able to debug like LISP allows for), but, even that, would not require much effort.

The issue here is that not many people are _willing_ to put forth the effort to do the extra work. I mean, if you really wanted to, with the preprocessor and a bit of implementation, we could be able to write the **entire** project in **pseudocode** and feed that to the C compiler. Hell, the backend (magical hacky tree-y stuff) could be written in C, and then just have one file with all of the pseudocode. You see, the thing about C is it's just really, really extendable, yet still extremely fast [and therefore somewhat awesome].

Now. Another thought. If we know all of the languages fully, in C, we have hardly any need to worry about pointers.

For me, C is a clear winner just because of how much we can do with it. Yes, LISP is great because of how little code you have to write, but to me it's also harder to understand for the average person reading our code, and it's still like a lot slower than C.

We have to consider what we can actually do. While the other languages have the "basics" pre-built-in (like advanced magical arrays, etc.), with a couple of function definitions, one can duplicate such behavior in C without hardly any troubles. Translating that into pseudo-code for our paper (which I assume we are for the project) will be relatively simple.

Also, when you're writing in C, I would disagree that memory has to be thought-of carefully. It's a thing, and once you've got enough experience with it, you just accept the, like, one or two malloc calls you have to write for each type or object. Not hard. Then it's just keeping track of pointers. As much as that is brainfuck for some people, it's still very possible to do. It takes _pretty-much just enough_ work off the programmer's back to take care of the important memory handling, but it's still up to the programmer to keep track of their memory.

I wrote [a gist](https://gist.github.com/four04/6325694) a while ago to help (sorta). If you want me to update it with more stuff so you can print it out and read it when and if you're having memory-related problems, I'd be glad to.

**Comment by cg505** [comment]
Feel free to update the issue with corrections if you believe what I have put there isn't fully accurate and you know better than I. But I agree that down here is the correct place to converse about opinion clashes. When I get a chance, I will respond to what you just wrote with some questions, but I'm a little busy right now.

**Comment by cg505** [comment]
Oops

**Comment by rye** [comment]
I should add, strcmp doesn't return the opposite of expected values; traditionally, Unix's built-in true (not from `stdbool.h`, but the manual actual `TRUE` value has been zero). `strcmp` conforms to that tradition. Therefore, when you `return 0;` from your main function, you're returning "true" to the operating system; anything else is not "true" and signifies that something was not correct.

EDIT: Coming from every other language invented that uses the `true == 1` philosophy, I can see how that's not expected. I thought the same. Generally we don't `!strcmp(str1, str2)`, we just `strcmp(str1, str2) == 0` because the value returned [depends on whether the first character that does not match has or does not have a greater value in `str1` than in `str2`](http://www.cplusplus.com/reference/cstring/strcmp/).

EDIT: Therefore, `strcmp` returns something more like a difference between the strings than a boolean value.

**Comment by rye** [comment]
I've added some of this stuff to the wiki.

**Comment by rye** [comment]
I think most of the problem was with the algorithm for Ruby--I've been doing some Project Euler over in Ruby recently, and I've found that things like finding prime factors (even more complicated than generating 10,000 primes) are actually extremely fast (0.058 real seconds) now. Ruby is just awesome.

**Comment by cg505** [comment]
It's a little strange, because most people online seem to have the
impression that Ruby is significantly slower than lisp.

**Comment by rye** [comment]
That is silly; it's not true at all. It's become apparent that Ruby is **fast**.

**Comment by rye** [comment]
I'll close this issue, now, over 2 years later. Nothing really useful to talk about anymore.
