### ISSUE TITLE
C doesn't seem to compile

### ISSUE THREAD

**Issue by cg505** [kotct/language-comparison#3]
Maybe I'm doing it wrong? Almost definitely.
What commands are you using?

**Comment by rye** [comment]
What's it saying?

**Comment by rye** [comment]
`gcc -o main.bin main.c -ggdb -lm -std=c11`

**Comment by rye** [comment]
Well, that's what I remember.

**Comment by cg505** [comment]
That works.
I think I didn't have the `-lm`.
